name: flutter_remote_ui_kit
description: A production-ready Flutter package that enables a fully JSON-driven, remote-configurable UI system.
version: 1.0.1
homepage: https://github.com/example/flutter_remote_ui
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  uuid: ^4.0.0
  logging: ^1.2.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
